name: scrape daily

on:
  schedule:
    - cron: "0 6 * * *" # todos os dias às 6h UTC
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: install deps
        run: npm ci

      - name: install playwright deps
        run: npx playwright install --with-deps

      - name: run scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: npx tsx jobs/scrape.ts
